services:
  - type: web
    name: codehost
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 4 --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: ADMIN_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.9"
    disk:
      name: codehost-data
      mountPath: /app/data
      sizeGB: 1
